export const achievementData = [
  {
    title: "Product Manager",
    subTitle: "Phygtl. (Feb 2025 - Present)",
    result: "Coming Soon...",
    des: "Recently selected as an Intern with responsibilities that will evolve further. More details coming soon.",
  },
  {
    title: "Software Engineer",
    subTitle: "Flowscript.AI (Oct 2024 - Present)",
    result: "Success",
    des: "",
    tags: [
      "App Development",
      "UI/UX Consistency",
      "Cross-Device Compatibility",
      "Security Enhancement",
      "REST API Integration",
      "Navigation Improvement",
      "Visual Hierarchy Optimization",
      "Responsive Design",
      "UI Component Optimization",
      "User Experience Enhancement",
      "Agile Collaboration",
      "Code Reviews",
      "Backend Integration",
      "Technical Documentation",
      "Onboarding Support",
    ],
  },
  {
    title: "Full Stack Web Developer",
    subTitle: "JS Associates (May 2020 - May 2022)",
    result: "Success",
    des: "",
    tags: [
      "Performance Optimization",
      "Page Load Speed Improvement",
      "Boost User Engagement",
      "Refactor Legacy Code",
      "UI/UX Collaboration",
      "Responsive Web Design",
      "Reduce Bounce Rates",
      "Cross-Browser Compatibility",
      "Build Reusable Components",
      "Build Design Systems",
      "API Integration & State Management",
      "Backend Collaboration",
      "Production Issue Troubleshoots",
      "Downtime Reduction",
      "Automated Testing",
      "Version Control",
      "Code Reviews",
      "Mentorship",
      "Agile Methodologies",
      "Project Management",
      "Documentation",
      "Onboarding Optimization",
    ],
  },
];
