import projectOne from "../../../assets/images/Webp/projectOne.webp";
import projectTwo from "../../../assets/images/Webp/projectTwo.webp";
import projectThree from "../../../assets/images/Webp/projectThree.webp";
import ProjectDetail from "../ProjectDetail";

export const projectsData = [
  {
    "all-categories": [
      {
        id: "a1",
        src: projectOne,
        title: "Task Management App",
        des: "A full-fledged task management app with drag-and-drop functionality, deadline tracking, and user authentication.",
        github: "https://github.com/Ashwin-Pulipati",
        website: "https://task-manager-app.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "a2",
        src: projectTwo,
        title: "AI Chatbot Assistant",
        des: "A chatbot powered by OpenAI API that helps users automate responses and interact intelligently.",
        github: "https://github.com/Ashwin-Pulipati",
        website: "https://ai-chatbot-assistant.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
    ],
  },
  {
    "frontend-development": [
      {
        id: "f1",
        src: projectThree,
        title: "E-commerce Product Page",
        des: "A responsive and interactive product page with filters, sorting, and real-time price updates.",
        github: "https://github.com/Ashwin-Pulipati",
        website: "https://ecommerce-product-page.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "f2",
        src: projectOne,
        title: "Portfolio Website",
        des: "A modern portfolio website showcasing animations, dark mode, and contact form integration.",
        github: "https://github.com/Ashwin-Pulipati",
        website: "https://personal-portfolio.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
    ],
  },
  {
    "full-stack-development": {
      "all-stacks": [
        {
          id: "mern1",
          src: projectTwo,
          title: "MERN Task Manager",
          des: "A MERN stack app with user auth, CRUD operations, and task tracking.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://mern-task-manager.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
        {
          id: "mean1",
          src: projectOne,
          title: "MEAN Expense Tracker",
          des: "Track expenses using a MEAN stack app with real-time updates.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://mean-expense-tracker.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
        {
          id: "pern1",
          src: projectThree,
          title: "PERN Blog Engine",
          des: "Create and edit blogs in this full-stack PERN platform with PostgreSQL.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://pern-blog-engine.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
        {
          id: "py1",
          src: projectTwo,
          title: "Flask Job Board",
          des: "Job listing platform built with Flask and SQLAlchemy.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://flask-job-board.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
        {
          id: "java1",
          src: projectOne,
          title: "Spring Boot E-commerce",
          des: "Full-featured shopping site using Spring Boot and Thymeleaf.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://spring-boot-ecommerce.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
      ],
      "mern-stack": [
        {
          id: "mern1",
          src: projectTwo,
          title: "MERN Task Manager",
          des: "A MERN stack app with user auth, CRUD operations, and task tracking.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://mern-task-manager.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
      ],
      "mean-stack": [
        {
          id: "mean1",
          src: projectOne,
          title: "MEAN Expense Tracker",
          des: "Track expenses using a MEAN stack app with real-time updates.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://mean-expense-tracker.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
      ],
      "pern-stack": [
        {
          id: "pern1",
          src: projectThree,
          title: "PERN Blog Engine",
          des: "Create and edit blogs in this full-stack PERN platform with PostgreSQL.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://pern-blog-engine.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
      ],
      python: [
        {
          id: "py1",
          src: projectTwo,
          title: "Flask Job Board",
          des: "Job listing platform built with Flask and SQLAlchemy.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://flask-job-board.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
      ],
      java: [
        {
          id: "java1",
          src: projectOne,
          title: "Spring Boot E-commerce",
          des: "Full-featured shopping site using Spring Boot and Thymeleaf.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://spring-boot-ecommerce.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
      ],
    },
  },
  {
    "machine-learning": [
      {
        id: "ml1",
        src: projectOne,
        title: "Image Classifier",
        des: "A deep learning model to classify images using TensorFlow.js and pre-trained models.",
        github: "https://github.com/Ashwin-Pulipati",
        website: "https://image-classifier.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "ml2",
        src: projectTwo,
        title: "Stock Market Predictor",
        des: "A machine learning model to analyze stock trends and predict future prices.",
        github: "https://github.com/Ashwin-Pulipati",
        website: "https://stock-market-predictor.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
    ],
  },
  {
    "ui-ux": [
      {
        id: "u1",
        src: projectThree,
        title: "Mobile Banking App UI",
        des: "A conceptual UI/UX design for a mobile banking app with smooth animations and accessibility features.",
        github: "https://github.com/Ashwin-Pulipati",
        website: "https://banking-app-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u2",
        src: projectOne,
        title: "Travel Booking App UI",
        des: "A travel booking app prototype with intuitive navigation and an engaging user experience.",
        github: "https://github.com/Ashwin-Pulipati",
        website: "https://travel-booking-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
    ],
  },
  {
    ai: {
      "all-ai": [
        {
          id: "nc1",
          src: projectTwo,
          title: "Automation youtube",
          des: "A MERN stack app with user auth, CRUD operations, and task tracking.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://mern-task-manager.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
        {
          id: "cb1",
          src: projectOne,
          title: "Hugging Face Gradio",
          des: "Track expenses using a MEAN stack app with real-time updates.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://mean-expense-tracker.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
      ],
      "no-code": [
        {
          id: "nc1",
          src: projectTwo,
          title: "Automation youtube",
          des: "A MERN stack app with user auth, CRUD operations, and task tracking.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://mern-task-manager.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
      ],
      "code-based": [
        {
          id: "cb1",
          src: projectOne,
          title: "Hugging Face Gradio",
          des: "Track expenses using a MEAN stack app with real-time updates.",
          github: "https://github.com/Ashwin-Pulipati",
          website: "https://mean-expense-tracker.netlify.app/",
          createdAt: new Date().toISOString(),
          component: ProjectDetail,
        },
      ],
    },
  },
];