import projectOne from "../../../assets/images/Webp/projectOne.webp";
import projectTwo from "../../../assets/images/Webp/projectTwo.webp";
import projectThree from "../../../assets/images/Webp/projectThree.webp";
import ProjectDetail from "../ProjectDetail";

export const projectsData = [
  {
    "all-categories": [
      {
        id: "a1",
        src: projectOne,
        title: "Task Management App",
        des: "A full-fledged task management app with drag-and-drop functionality, deadline tracking, and user authentication.",
        github: "https://github.com/example/task-manager",
        website: "https://task-manager-app.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "a2",
        src: projectTwo,
        title: "AI Chatbot Assistant",
        des: "A chatbot powered by OpenAI API that helps users automate responses and interact intelligently.",
        github: "https://github.com/example/ai-chatbot",
        website: "https://ai-chatbot-assistant.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
    ],
  },
  {
    "frontend-development": [
      {
        id: "f1",
        src: projectThree,
        title: "E-commerce Product Page",
        des: "A responsive and interactive product page with filters, sorting, and real-time price updates.",
        github: "https://github.com/example/ecommerce-page",
        website: "https://ecommerce-product-page.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "f2",
        src: projectOne,
        title: "Portfolio Website",
        des: "A modern portfolio website showcasing animations, dark mode, and contact form integration.",
        github: "https://github.com/example/portfolio",
        website: "https://personal-portfolio.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
    ],
  },
  {
    "mern-stack-development": [
      {
        id: "ms1",
        src: projectTwo,
        title: "Blogging Platform",
        des: "A full-stack blog platform with authentication, user roles, and markdown support.",
        github: "https://github.com/example/blogging-platform",
        website: "https://mern-blog-platform.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "ms2",
        src: projectThree,
        title: "Real-time Chat App",
        des: "A real-time chat application using WebSockets for seamless messaging and notifications.",
        github: "https://github.com/example/chat-app",
        website: "https://real-time-chat-app.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
    ],
  },
  {
    "machine-learning": [
      {
        id: "ml1",
        src: projectOne,
        title: "Image Classifier",
        des: "A deep learning model to classify images using TensorFlow.js and pre-trained models.",
        github: "https://github.com/example/image-classifier",
        website: "https://image-classifier.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "ml2",
        src: projectTwo,
        title: "Stock Market Predictor",
        des: "A machine learning model to analyze stock trends and predict future prices.",
        github: "https://github.com/example/stock-predictor",
        website: "https://stock-market-predictor.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
    ],
  },
  {
    "ui-ux": [
      {
        id: "u1",
        src: projectThree,
        title: "Mobile Banking App UI",
        des: "A conceptual UI/UX design for a mobile banking app with smooth animations and accessibility features.",
        github: "https://github.com/example/banking-ui",
        website: "https://banking-app-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u2",
        src: projectOne,
        title: "Travel Booking App UI",
        des: "A travel booking app prototype with intuitive navigation and an engaging user experience.",
        github: "https://github.com/example/travel-ui",
        website: "https://travel-booking-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u3",
        src: projectThree,
        title: "Mobile Banking App UI",
        des: "A conceptual UI/UX design for a mobile banking app with smooth animations and accessibility features.",
        github: "https://github.com/example/banking-ui",
        website: "https://banking-app-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u4",
        src: projectOne,
        title: "Travel Booking App UI",
        des: "A travel booking app prototype with intuitive navigation and an engaging user experience.",
        github: "https://github.com/example/travel-ui",
        website: "https://travel-booking-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u5",
        src: projectThree,
        title: "Mobile Banking App UI",
        des: "A conceptual UI/UX design for a mobile banking app with smooth animations and accessibility features.",
        github: "https://github.com/example/banking-ui",
        website: "https://banking-app-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u6",
        src: projectOne,
        title: "Travel Booking App UI",
        des: "A travel booking app prototype with intuitive navigation and an engaging user experience.",
        github: "https://github.com/example/travel-ui",
        website: "https://travel-booking-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u7",
        src: projectThree,
        title: "Mobile Banking App UI",
        des: "A conceptual UI/UX design for a mobile banking app with smooth animations and accessibility features.",
        github: "https://github.com/example/banking-ui",
        website: "https://banking-app-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u8",
        src: projectOne,
        title: "Travel Booking App UI",
        des: "A travel booking app prototype with intuitive navigation and an engaging user experience.",
        github: "https://github.com/example/travel-ui",
        website: "https://travel-booking-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u9",
        src: projectThree,
        title: "Mobile Banking App UI",
        des: "A conceptual UI/UX design for a mobile banking app with smooth animations and accessibility features.",
        github: "https://github.com/example/banking-ui",
        website: "https://banking-app-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
      {
        id: "u10",
        src: projectOne,
        title: "Travel Booking App UI",
        des: "A travel booking app prototype with intuitive navigation and an engaging user experience.",
        github: "https://github.com/example/travel-ui",
        website: "https://travel-booking-ui.netlify.app/",
        createdAt: new Date().toISOString(),
        component: ProjectDetail,
      },
    ],
  },
];